RPC:
  Port: 8000
  # 聚合时间
  AggregationTime: 5
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: 1m
  Password: 11
  IsSSL: true
  From: 122786302@qq.com
  To:
    - lhy122786302@gmail.com
ReportDB:
  DBType: mongodb
  Host: 127.0.0.1:27018
  DBName: athena-server
RuleDB:
  DBType: mysql
  Username: root
  Password: 123456
  Host: 127.0.0.1:3307
  DBName: rule-server
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

